# Generated by Django 5.2.1 on 2025-05-24 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_factura_options_factura_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='core.cita'),
        ),
    ]
